### ISSUE TITLE
Possibly unhandled error

### ISSUE THREAD

**Issue by neojski** [pouchdb/mapreduce#153]
``` bash
TEST_DB=testdb mocha -g 'Test basic view$' test/test.js
```

results in

```
  ․Possibly unhandled TypeError: Cannot read property 'rev_tree' of undefined
    at updateDoc (/home/neo/mapreduce/node_modules/pouchdb/lib/adapters/leveldb.js:385:27)
    at /home/neo/mapreduce/node_modules/pouchdb/lib/adapters/leveldb.js:358:11
    at dispatchError (/home/neo/mapreduce/node_modules/pouchdb/node_modules/levelup/lib/util.js:131:7)
    at LevelUP.get (/home/neo/mapreduce/node_modules/pouchdb/node_modules/levelup/lib/levelup.js:177:12)
    at SubDB.SDB.get (/home/neo/mapreduce/node_modules/pouchdb/node_modules/level-sublevel/sub.js:73:14)
    at processDocs (/home/neo/mapreduce/node_modules/pouchdb/lib/adapters/leveldb.js:346:23)
    at PouchDB.LevelPouch.api._bulkDocs (/home/neo/mapreduce/node_modules/pouchdb/lib/adapters/leveldb.js:609:5)
    at PouchDB.<anonymous> (/home/neo/mapreduce/node_modules/pouchdb/lib/adapter.js:707:15)
    at PouchDB.<anonymous> (/home/neo/mapreduce/node_modules/pouchdb/lib/utils.js:437:21)
    at PouchDB.<anonymous> (/home/neo/mapreduce/node_modules/argsarray/index.js:14:18)
    at /home/neo/mapreduce/node_modules/pouchdb/lib/utils.js:402:21
    at tryCatch2 (/home/neo/mapreduce/node_modules/pouchdb/node_modules/bluebird/js/main/util.js:74:19)
    at Promise$_resolveFromResolver [as _resolveFromResolver] (/home/neo/mapreduce/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:608:13)
    at new Promise (/home/neo/mapreduce/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:88:37)
    at PouchDB.<anonymous> (/home/neo/mapreduce/node_modules/pouchdb/lib/utils.js:389:19)
    at PouchDB.bulkDocs (/home/neo/mapreduce/node_modules/argsarray/index.js:14:18)
    at /home/neo/mapreduce/test/test.js:192:21
    at tryCatch1 (/home/neo/mapreduce/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/home/neo/mapreduce/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/neo/mapreduce/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/neo/mapreduce/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/home/neo/mapreduce/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/neo/mapreduce/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/home/neo/mapreduce/node_modules/bluebird/js/main/async.js:37:14)
    at process._tickDomainCallback (node.js:463:13)
․

  2 passing (33ms)
```

**Comment by nolanlawson** [comment]
fixed now AFAICT
